# HTTP Requests for Testing the API
# This file contains a series of HTTP requests to test the API endpoints
# Just for convenience api usage, we dont test the API here (ie no check for errors test cases)

### Variables
#@apiUrl = http://127.0.0.1:8016/api
@apiUrl = https://unescopilot.com/api

### Get all sites
GET {{apiUrl}}/sites

### Search sites by general query (name or country)
GET {{apiUrl}}/sites?q=paris

### Search sites by name
GET {{apiUrl}}/sites?name=toto

### Search sites by geographic bounds (rectangle)
GET {{apiUrl}}/sites?minLat=48.0&maxLat=49.0&minLon=2.0&maxLon=3.0

### Search sites in Europe (approximate bounds)
GET {{apiUrl}}/sites?minLat=35.0&maxLat=70.0&minLon=-10.0&maxLon=40.0

### Search sites with multiple criteria (name + geographic bounds)
GET {{apiUrl}}/sites?name=château&minLat=45.0&maxLat=50.0&minLon=0.0&maxLon=8.0

### Get specific site by ID (using id_number from XML data)
GET {{apiUrl}}/sites/1133

### User Registration - Success
POST {{apiUrl}}/security/register
Content-Type: application/json

{
  "email": "test@test.com",
  "pseudo": "test",
  "password": "azeaze"
}

### User Login - Success
POST {{apiUrl}}/security/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "azeaze"
}

### Get current user info
# First login to get a token, then use it here
GET {{apiUrl}}/me
Authorization: Bearer ecb470bfd8412de91c719f90f720ae1122bfb971ce108418463b60dde88dc7ea

### Add a visit
POST {{apiUrl}}/visits
Content-Type: application/json
Authorization: Bearer ecb470bfd8412de91c719f90f720ae1122bfb971ce108418463b60dde88dc7ea

{
  "siteId": 1133,
  "visitDate": "2024-07-15"
}

### Get user's visits
GET {{apiUrl}}/visits
Authorization: Bearer ecb470bfd8412de91c719f90f720ae1122bfb971ce108418463b60dde88dc7ea

### Delete a visit
DELETE {{apiUrl}}/visits/1
Authorization: Bearer ecb470bfd8412de91c719f90f720ae1122bfb971ce108418463b60dde88dc7ea
